import { registerAgentHandlers } from "./agents.js";
import { registerApiKeyHandlers } from "./apiKeys.js";
import { registerAuditLogHandlers } from "./auditLogs.js";
import { registerAuthHandlers } from "./auth.js";
import { registerBillingHandlers } from "./billing.js";
import { registerExtensionHandlers } from "./extensions.js";
import { registerFileHandlers } from "./files.js";
import { registerFilePreviewHandlers } from "./filePreview.js";
import { registerConversationHandlers } from "./conversations.js";
import { registerHtmlPreviewHandlers } from "./htmlPreview.js";
import { registerKnowledgeHandlers } from "./knowledge.js";
import { registerLlmHandlers } from "./llm.js";
import { registerMarketToolHandlers } from "./marketTools.js";
import { registerMessageHandlers } from "./messages.js";
import { registerNotificationHandlers } from "./notifications.js";
import { registerOwleryHandlers } from "./owlery.js";
import { registerParseDocumentHandlers } from "./parseDocument.js";
import { registerSecretHandlers } from "./secrets.js";
import { registerSettingsHandlers } from "./settings.js";
import { registerShellHandlers } from "./shell.js";
import { registerTaskHandlers } from "./tasks.js";
import { registerTeamHandlers } from "./teams.js";
import { registerWebhookHandlers } from "./webhooks.js";
import { registerWindowHandlers } from "./window.js";
import { registerWorkflowHandlers } from "./workflows.js";

export function registerIpcHandlers(): void {
  registerAuthHandlers();
  registerSettingsHandlers();
  registerSecretHandlers();
  registerAgentHandlers();
  registerOwleryHandlers();
  registerConversationHandlers();
  registerMessageHandlers();
  registerTaskHandlers();
  registerWorkflowHandlers();
  registerKnowledgeHandlers();
  registerMarketToolHandlers();
  registerExtensionHandlers();
  registerTeamHandlers();
  registerBillingHandlers();
  registerNotificationHandlers();
  registerApiKeyHandlers();
  registerWebhookHandlers();
  registerAuditLogHandlers();
  registerFileHandlers();
  registerFilePreviewHandlers();
  registerHtmlPreviewHandlers();
  registerShellHandlers();
  registerLlmHandlers();
  registerParseDocumentHandlers();
  registerWindowHandlers();
}
