import type { MarketTool } from './types.js';

const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000);

/* ── 工具市场初始数据 ─────────────────────────────────────────────── */
export const MARKET_TOOLS: MarketTool[] = [
  {
    id: 'tool-1',
    name: 'Web 搜索',
    description: '实时检索全网信息，支持新闻、学术、商业多维度搜索',
    category: '调研',
    toolType: 'mcp',
    icon: 'Search',
    iconBg: 'from-cyan-500/30 to-blue-500/30',
    version: '2.1.0',
    developer: 'OwlOS 官方',
    rating: 4.9,
    installs: 128500,
    tags: ['调研'],
    installed: true,
    needsApiKey: false,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-2',
    name: 'Python 运行器',
    description: '沙箱环境中执行 Python 代码，支持数据分析与可视化库',
    category: '开发',
    toolType: 'cli',
    icon: 'Code2',
    iconBg: 'from-emerald-500/30 to-cyan-500/30',
    version: '1.5.2',
    developer: 'OwlOS 官方',
    rating: 4.8,
    installs: 98200,
    tags: ['开发'],
    installed: true,
    needsApiKey: false,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-3',
    name: 'GitHub 集成',
    description: '读写 GitHub 仓库，管理 PR、Issues，触发 CI/CD 流程',
    category: '开发',
    toolType: 'mcp',
    icon: 'GitBranch',
    iconBg: 'from-purple-500/30 to-pink-500/30',
    version: '3.0.1',
    developer: 'OwlOS 官方',
    rating: 4.7,
    installs: 76300,
    tags: ['开发'],
    installed: true,
    needsApiKey: true,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-4',
    name: '图表生成',
    description: '根据数据自动生成柱状图、折线图、饼图等多种可视化图表',
    category: '调研',
    toolType: 'cli',
    icon: 'BarChart3',
    iconBg: 'from-amber-500/30 to-orange-500/30',
    version: '1.2.0',
    developer: 'OwlOS 官方',
    rating: 4.6,
    installs: 54100,
    tags: ['调研'],
    installed: true,
    needsApiKey: false,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-5',
    name: 'Slack 通知',
    description: '向 Slack 频道发送消息、卡片与工作流通知',
    category: '通信',
    toolType: 'mcp',
    icon: 'MessageSquare',
    iconBg: 'from-rose-500/30 to-pink-500/30',
    version: '2.0.4',
    developer: 'Slack Inc.',
    rating: 4.5,
    installs: 43200,
    tags: ['通信'],
    installed: false,
    needsApiKey: true,
    official: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-6',
    name: 'PDF 解析器',
    description: '高精度解析 PDF 文档内容，支持表格、图表文字提取',
    category: '设计',
    toolType: 'cli',
    icon: 'FileText',
    iconBg: 'from-red-500/30 to-rose-500/30',
    version: '1.8.0',
    developer: 'DocAI Labs',
    rating: 4.4,
    installs: 31800,
    tags: ['设计'],
    installed: false,
    needsApiKey: false,
    official: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-7',
    name: 'SQL 查询',
    description: '连接主流数据库，执行 SQL 查询并返回结构化结果',
    category: '调研',
    toolType: 'cli',
    icon: 'Database',
    iconBg: 'from-blue-500/30 to-indigo-500/30',
    version: '2.3.1',
    developer: 'DataFlow',
    rating: 4.7,
    installs: 28900,
    tags: ['调研'],
    installed: false,
    needsApiKey: true,
    official: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-8',
    name: '邮件发送',
    description: '使用 SMTP 或 SendGrid 发送格式化邮件与附件',
    category: '通信',
    toolType: 'cli',
    icon: 'Mail',
    iconBg: 'from-teal-500/30 to-cyan-500/30',
    version: '1.1.2',
    developer: 'MailForge',
    rating: 4.3,
    installs: 22400,
    tags: ['通信'],
    installed: false,
    needsApiKey: true,
    official: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-9',
    name: 'Shell 执行器',
    description: '在隔离环境中执行 Shell 脚本，支持管道与文件操作',
    category: '通用',
    toolType: 'cli',
    icon: 'Code2',
    iconBg: 'from-slate-500/30 to-gray-500/30',
    version: '1.0.3',
    developer: 'OwlOS 官方',
    rating: 4.5,
    installs: 19800,
    tags: ['通用'],
    installed: false,
    needsApiKey: false,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-10',
    name: 'Browser Use',
    description: '通过 MCP 协议控制浏览器，实现网页自动化与数据抓取',
    category: '通用',
    toolType: 'mcp',
    icon: 'Shield',
    iconBg: 'from-violet-500/30 to-indigo-500/30',
    version: '0.9.1',
    developer: 'BrowserAI',
    rating: 4.6,
    installs: 17300,
    tags: ['通用'],
    installed: false,
    needsApiKey: false,
    official: false,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
  {
    id: 'tool-11',
    name: '知识召回',
    description: '从本地知识库中语义检索相关片段，支持 RAG 增强对话',
    category: '调研',
    toolType: 'cli',
    icon: 'Search',
    iconBg: 'from-cyan-500/30 to-emerald-500/30',
    version: '2.0.0',
    developer: 'OwlOS 官方',
    rating: 4.8,
    installs: 15600,
    tags: ['调研'],
    installed: false,
    needsApiKey: false,
    official: true,
    createdAt: daysAgo(90),
    updatedAt: daysAgo(10),
  },
];
