import type Database from "better-sqlite3";
import * as queries from "../queries/index.js";
import type { Agent } from "../types.js";
import { now } from "./utils.js";

export function seedAgents(db: Database.Database): void {
  const count = db.prepare("SELECT COUNT(*) FROM agents").pluck().get() as number;
  if (count > 0) return;

  const agents: Agent[] = [
    {
      id: "aria",
      name: "Aria",
      role: "aria",
      description: "协调员 · 负责任务拆解与团队调度",
      avatar: "A",
      color: "#a855f7",
      bgColor: "bg-purple-500/20",
      textColor: "text-purple-400",
      borderColor: "border-purple-500/40",
      status: "working",
      model: "GPT-4o",
      tools: ["web-search", "task-manager", "code-runner"],
      capabilities: ["任务协调", "自然语言理解", "多Agent调度"],
      triggerRule: "当任务涉及跨领域协作或需要多步骤规划时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "coder",
      name: "Coder",
      role: "coder",
      description: "代码专家 · 全栈开发与代码审查",
      avatar: "C",
      color: "#00f2c3",
      bgColor: "bg-cyan-500/20",
      textColor: "text-cyan-400",
      borderColor: "border-cyan-500/40",
      status: "working",
      model: "Claude 3.5 Sonnet",
      tools: ["code-runner", "github", "terminal"],
      capabilities: ["代码开发", "代码审查", "架构设计", "调试"],
      triggerRule: "当任务涉及编写、调试或审查代码时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "muse",
      name: "Muse",
      role: "muse",
      description: "创意设计师 · UI/UX 与品牌内容",
      avatar: "M",
      color: "#38bdf8",
      bgColor: "bg-blue-500/20",
      textColor: "text-blue-400",
      borderColor: "border-blue-500/40",
      status: "idle",
      model: "GPT-4o",
      tools: ["figma-plugin", "image-gen", "web-search"],
      capabilities: ["UI/UX 设计", "品牌设计", "文案创作", "视觉分析"],
      triggerRule: "当任务涉及设计、视觉创意或品牌内容时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "analyst",
      name: "Analyst",
      role: "analyst",
      description: "数据分析师 · 数据洞察与商业决策",
      avatar: "An",
      color: "#f59e0b",
      bgColor: "bg-amber-500/20",
      textColor: "text-amber-400",
      borderColor: "border-amber-500/40",
      status: "working",
      model: "GPT-4o",
      tools: ["python-runner", "sql-query", "chart-gen"],
      capabilities: ["数据分析", "可视化", "统计建模", "商业智能"],
      triggerRule: "当任务涉及数据处理、统计分析或商业报告时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "writer",
      name: "Writer",
      role: "writer",
      description: "资深文案 · 各类文档撰写与内容润色",
      avatar: "W",
      color: "#f43f5e",
      bgColor: "bg-rose-500/20",
      textColor: "text-rose-400",
      borderColor: "border-rose-500/40",
      status: "idle",
      model: "Claude 3.5 Sonnet",
      tools: ["web-search", "file-reader"],
      capabilities: ["文案撰写", "内容润色", "翻译", "总结"],
      triggerRule: "当任务涉及写作、翻译或内容创作时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "pm",
      name: "PM",
      role: "pm",
      description: "产品经理 · 需求分析与项目规划",
      avatar: "P",
      color: "#8b5cf6",
      bgColor: "bg-violet-500/20",
      textColor: "text-violet-400",
      borderColor: "border-violet-500/40",
      status: "working",
      model: "GPT-4o",
      tools: ["web-search", "task-manager"],
      capabilities: ["需求分析", "PRD撰写", "项目规划", "竞品调研"],
      triggerRule: "当任务涉及产品设计、需求分析或项目规划时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "ops",
      name: "Ops",
      role: "ops",
      description: "运维专家 · CI/CD 与基础设施管理",
      avatar: "O",
      color: "#10b981",
      bgColor: "bg-emerald-500/20",
      textColor: "text-emerald-400",
      borderColor: "border-emerald-500/40",
      status: "idle",
      model: "GPT-4o",
      tools: ["terminal", "github", "code-runner"],
      capabilities: ["CI/CD配置", "Docker", "K8s", "监控告警"],
      triggerRule: "当任务涉及部署、运维或基础设施时自动参与",
      enabled: false,
      createdAt: now(),
      updatedAt: now(),
    },
    {
      id: "designer",
      name: "Designer",
      role: "designer",
      description: "资深设计师 · UI/UX 与视觉规范",
      avatar: "D",
      color: "#f59e0b",
      bgColor: "bg-amber-500/20",
      textColor: "text-amber-400",
      borderColor: "border-amber-500/40",
      status: "idle",
      model: "Claude 3.5 Sonnet",
      tools: ["figma-plugin", "image-gen"],
      capabilities: ["UI设计", "UX优化", "设计规范", "原型评审"],
      triggerRule: "当任务涉及界面设计、视觉规范或用户体验时自动参与",
      enabled: true,
      createdAt: now(),
      updatedAt: now(),
    },
  ];

  for (const agent of agents) {
    queries.upsertAgent(db, agent);
  }
}
